name: eda_ia
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Data manipulation and analysis
  - pandas>=1.5.0
  - numpy>=1.20.0
  
  # Data visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  
  # Time series analysis
  - statsmodels>=0.13.0
  
  # Missing data visualization
  - missingno>=0.5.0
  
  # Jupyter notebook support
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - notebook>=6.4.0
  
  # System utilities (for wget, unzip commands)
  - wget
  
